src/Entity/Article.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $article_title;

    /**
     * @ORM\Column(type="text")
     */
    private $article_text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $article_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isConfirmed;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Author", inversedBy="article_id", fetch="EAGER")
     */
    private $authors;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article_id")
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->setArticleDate(new DateTime());
        $this->setIsConfirmed(false);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticleTitle(): ?string
    {
        return $this->article_title;
    }

    public function setArticleTitle(string $article_title): self
    {
        $this->article_title = $article_title;

        return $this;
    }

    public function getArticleText(): ?string
    {
        return $this->article_text;
    }

    public function setArticleText(string $article_text): self
    {
        $this->article_text = $article_text;

        return $this;
    }

    public function getArticleDate(): ?\DateTimeInterface
    {
        return $this->article_date;
    }

    public function setArticleDate(\DateTimeInterface $article_date): self
    {
        $this->article_date = $article_date;

        return $this;
    }

    public function getIsConfirmed(): ?bool
    {
        return $this->isConfirmed;
    }

    public function setIsConfirmed(bool $isConfirmed): self
    {
        $this->isConfirmed = $isConfirmed;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user;
    }

    public function setUserId(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Author[]
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
            $author->addArticleId($this);
        }
        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        if ($this->authors->contains($author)) {
            $this->authors->removeElement($author);
            $author->removeArticleId($this);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticleId($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticleId() === $this) {
                $comment->setArticleId(null);
            }
        }

        return $this;
    }


    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

}

src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $author_name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $author_first_name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $facebook_page;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $author_image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $creation_image;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Article", mappedBy="authors")
     */
    private $article_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FanArt", mappedBy="author")
     */
    private $fan_art_id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Job", inversedBy="author_id")
     */
    private $jobs;

    public function __construct()
    {
        $this->article_id = new ArrayCollection();
        $this->fan_art_id = new ArrayCollection();
        $this->jobs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthorName(): ?string
    {
        return $this->author_name;
    }

    public function setAuthorName(string $author_name): self
    {
        $this->author_name = $author_name;

        return $this;
    }

    public function getAuthorFirstName(): ?string
    {
        return $this->author_first_name;
    }

    public function setAuthorFirstName(string $author_first_name): self
    {
        $this->author_first_name = $author_first_name;

        return $this;
    }

    public function getFacebookPage(): ?string
    {
        return $this->facebook_page;
    }

    public function setFacebookPage(?string $facebook_page): self
    {
        $this->facebook_page = $facebook_page;

        return $this;
    }

    public function getAuthorImage(): ?string
    {
        return $this->author_image;
    }

    public function setAuthorImage(?string $author_image): self
    {
        $this->author_image = $author_image;

        return $this;
    }

    public function getCreationImage(): ?string
    {
        return $this->creation_image;
    }

    public function setCreationImage(?string $creation_image): self
    {
        $this->creation_image = $creation_image;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticleId(): Collection
    {
        return $this->article_id;
    }

    public function addArticleId(Article $articleId): self
    {
        if (!$this->article_id->contains($articleId)) {
            $this->article_id[] = $articleId;
        }

        return $this;
    }

    public function removeArticleId(Article $articleId): self
    {
        if ($this->article_id->contains($articleId)) {
            $this->article_id->removeElement($articleId);
        }

        return $this;
    }

    /**
     * @return Collection|FanArt[]
     */
    public function getFanArtId(): Collection
    {
        return $this->fan_art_id;
    }

    public function addFanArtId(FanArt $fanArtId): self
    {
        if (!$this->fan_art_id->contains($fanArtId)) {
            $this->fan_art_id[] = $fanArtId;
            $fanArtId->setAuthor($this);
        }

        return $this;
    }

    public function removeFanArtId(FanArt $fanArtId): self
    {
        if ($this->fan_art_id->contains($fanArtId)) {
            $this->fan_art_id->removeElement($fanArtId);
            // set the owning side to null (unless already changed)
            if ($fanArtId->getAuthor() === $this) {
                $fanArtId->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Job[]
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): self
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs[] = $job;
            $job->addAuthorId($this);
        }

        return $this;
    }

    public function removeJob(Job $job): self
    {
        if ($this->jobs->contains($job)) {
            $this->jobs->removeElement($job);
            $job->removeAuthorId($this);
        }

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment_article;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment_fan_art;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="comments")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="comments")
     * @ORM\JoinColumn(nullable=true)
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\FanArt", inversedBy="comments")
     * @ORM\JoinColumn(nullable=true)
     */
        private $fan_art;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isConfirmed;

    public function __construct()
    {
        $this->setIsConfirmed(true);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentArticle(): ?string
    {
        return $this->comment_article;
    }

    public function setCommentArticle(string $comment_article): self
    {
        $this->comment_article = $comment_article;

        return $this;
    }

    public function getCommentFanArt(): ?string
    {
        return $this->comment_fan_art;
    }

    public function setCommentFanArt(string $comment_fan_art): self
    {
        $this->comment_fan_art = $comment_fan_art;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user;
    }

    public function setUserId(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getArticleId(): ?Article
    {
        return $this->article;
    }

    public function setArticleId(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getFanArtId(): ?FanArt
    {
        return $this->fan_art;
    }

    public function setFanArtId(?FanArt $fan_art): self
    {
        $this->fan_art = $fan_art;

        return $this;
    }

    public function getIsConfirmed(): ?bool
    {
        return $this->isConfirmed;
    }

    public function setIsConfirmed(bool $isConfirmed): self
    {
        $this->isConfirmed = $isConfirmed;

        return $this;
    }
}

src/Entity/FanArt.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FanArtRepository")
 */
class FanArt
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fan_art_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fan_art_hook;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fan_art_sketch;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isConfirmed;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Author", inversedBy="fan_art_id")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="fan_art_id")
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="fanArts")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Editor", mappedBy="fanArts")
     */
    private $editor_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->editor_id = new ArrayCollection();
        $this->setIsConfirmed(false);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFanArtTitle(): ?string
    {
        return $this->fan_art_title;
    }

    public function setFanArtTitle(string $fan_art_title): self
    {
        $this->fan_art_title = $fan_art_title;

        return $this;
    }

    public function getFanArtHook(): ?string
    {
        return $this->fan_art_hook;
    }

    public function setFanArtHook(?string $fan_art_hook): self
    {
        $this->fan_art_hook = $fan_art_hook;

        return $this;
    }

    public function getFanArtSketch(): ?string
    {
        return $this->fan_art_sketch;
    }

    public function setFanArtSketch(string $fan_art_sketch): self
    {
        $this->fan_art_sketch = $fan_art_sketch;

        return $this;
    }

    public function getIsConfirmed(): ?bool
    {
        return $this->isConfirmed;
    }

    public function setIsConfirmed(bool $isConfirmed): self
    {
        $this->isConfirmed = $isConfirmed;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setFanArtId($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getFanArtId() === $this) {
                $comment->setFanArtId(null);
            }
        }

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user;
    }

    public function setUserId(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Editor[]
     */
    public function getEditorId(): Collection
    {
        return $this->editor_id;
    }

    public function addEditorId(Editor $editorId): self
    {
        if (!$this->editor_id->contains($editorId)) {
            $this->editor_id[] = $editorId;
        }

        return $this;
    }

    public function removeEditorId(Editor $editorId): self
    {
        if ($this->editor_id->contains($editorId)) {
            $this->editor_id->removeElement($editorId);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

templates/pages/article.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mb-5 mt-5">
        <div class="articletitle">
            <h1 class="mb-5">{{ article.articleTitle }}</h1>
        </div>
        <div class="articletext">
            <h3 class="mb-5">{{ article.articleText }}</h3>
        </div>
    </div>

    <div class="col mt-3" style="text-align: center">
            {%  for author in article.authors %}
                <a href="{{ path('author', {id : author.id}) }}">  <p>{{ author.authorName }}</p></a>
            {% endfor %}


    {% if app.user %}
        <button class="btn btn-light btn-link"><a href="{{ path('dashboard_articles_update', {slug : article.slug}) }}">Modifier</a></button>
    {% endif %}

    </div>

    <div class="container formcomment mb-5 mt-5">

        <h3>Ajouter un commentaire : </h3>

        {{ form_start(commentForm) }}

                <div class="col-12 mt-3">
                    {{ form_row(commentForm.comment_article, {'attr': {class : "form-control"}}) }}
                </div>
                <div class="col-6 mt-3">
                    {{ form_row(commentForm.valider, {'attr' : {class : "btn btn-primary"}}) }}
                </div>
        {{ form_end(commentForm) }}
    </div>



    <div class="container formcomment mb-5 mt-5">

        <h3>Commentaires : </h3>

        {% for comment in comments %}

            <div>
                {{ comment.commentArticle }}
            </div>

            <div>
                <p>Publié par {{ comment.userId.pseudo }}</p>
            </div>
        {% endfor %}

    </div>



{% endblock %}

templates/pages/articles.html.twig
{% extends "base.html.twig" %}

{% block styleFanArts %}
    <link rel="stylesheet" href="{{ asset ("styles/fanarts.styles.css")}}">
{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-3 mt-4" style="background: #101fff; border-right: 3px solid">
                {% include "pages/parts/sidebar.html.twig" %}
            </div>

            <div class="col-9">
                <div class="row justify-content-center mt-4 mb-4">
                    {% for article in articles %}
                        <div class="col-md-4 p-2">
                        <div class="elements">
                            <p>{{ article.articleTitle }}</p>
                            <div class="text">
                                <p>{{ article.articleText|length > 30 ? article.articleText(0, 30) ~ '...' : article.articleText }}</p>
                            </div>
                            <a href="{{ path("article", {slug : article.slug}) }}" class="btn btn-secondary">Voir</a>
                        </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="container mt-3 mb-5">
                <div class="row">
                    <div class="col-6">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-4">
                                    {% if from > 1 %}
                                        <a href="{{path('articles', {from : from - 1}) }}" class="btn-lg btn-dark">Précédent</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-4">
                                    <a href="{{ path('articles', {from : from + 1}) }}" class="btn-lg btn-dark buttons">Suivant</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/author.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% block styleFanArts %}
        <link rel="stylesheet" href="{{ asset ("styles/home.styles.css")}}">
    {% endblock %}

    <div class="container-fluid">
        <div class="authorname">
            <div class="col-12">
                <p id="authorname"> {{ author.authorFirstName }} {{ author.authorName }} </p>
                <p id="authorname">Facebook page: {{ author.facebookPage }}</p>
            </div>
        </div>
    </div>
    <div class="container authorimg">
        <img src="/uploads/images/{{ author.authorImage }}" height= 350px alt="image de l'artiste">
    </div>
    <div class="container authorart">
        <img src="/uploads/images/{{ author.creationImage }}" height= 350px alt="dessin de l'artiste">
    </div>

{% endblock %}

templates/pages/fanart.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container mb-5 mt-5">
    <div class="fanarttitle">
       <h1 class="mb-5">{{ fanArt.fanArtTitle }}</h1>
    </div>
    <div class="fanartimg">
        <img src="/uploads/images/{{ fanArt.fanArtSketch }}" alt="Sketch Fan-Art">
    </div>
        <div class="fanarthook">
        <h3 class="mb-5">{{ fanArt.fanArtHook }}</h3>
        </div>
    </div>

    <div class="col mt-3" style="text-align: center">
        {% if app.user %}
        <button class="btn btn-light btn-link"><a href="{{ path('dashboard_fanArts_update', {'slug': fanArt.slug}) }}">Mettre à jour</a></button>
        {% endif %}
    </div>

    <div class="container formcomment mb-5 mt-5">

        <h3>Ajouter un commentaire : </h3>

        {{ form_start(commentForm) }}

        <div class="col-12 mt-3">
            {{ form_row(commentForm.comment_fan_art, {'attr': {class : "form-control"}}) }}
        </div>
        <div class="col-6 mt-3">
            {{ form_row(commentForm.ajouter, {'attr' : {class : "btn btn-primary"}}) }}
        </div>
        {{ form_end(commentForm) }}
    </div>

    <div class="container formcomment mb-5 mt-5">
        <h3>Commentaires : </h3>
        {% for comment in comments %}
            <div>
                {{ comment.commentFanArt }}
            </div>
            <div>
                <p>Publié par {{ comment.userId.pseudo }}</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/pages/fanarts.html.twig
{% extends "base.html.twig" %}

{% block styleFanArts %}
    <link rel="stylesheet" href="{{ asset ("styles/fanarts.styles.css")}}">
{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-3 mt-4" style="background: #101fff; border-right: 3px solid">
                {% include "pages/parts/sidebar.html.twig" %}
            </div>
            <div class="col-9">
                <div class="row justify-content-center mt-4 mb-4">
                    {% for fanArt in fanArts %}
                        <div class="col-md-4 p-2">
                            <div class="elements">
                                <p>{{ fanArt.fanArtTitle }}</p>
                                <img src="/uploads/images/{{ fanArt.fanArtSketch }}" alt="">
                                <div class="text">
                                    <p>{{ fanArt.fanArtHook|length > 30 ? fanArt.fanArtHook|slice(0, 30) ~ '...' : fanArt.fanArtHook }}</p>
                                </div>
                                <a href="{{ path("fanArt", {slug : fanArt.slug}) }}" class="btn btn-secondary">Voir</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="container mt-3 mb-5">
                    <div class="row">
                        <div class="col-6">
                            <div class="container">
                                <div class="row justify-content-center">
                                    <div class="col-4">
                                        {% if from > 1 %}
                                            <a href="{{path('fanArts', {from : from - 1}) }}" class="btn-lg btn-dark">Précédent</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="container">
                                <div class="row justify-content-center">
                                    <div class="col-4">
                                        <a href="{{ path('fanArts', {from : from + 1}) }}" class="btn-lg btn-dark buttons">Suivant</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/pages/signup.html.twig
{% extends 'base.html.twig' %}

{% block styleSignUp %}
    <link rel="stylesheet" href="{{ asset ("styles/create-fanart.styles.css")}}">
{% endblock %}

{% block body %}
 
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-7 col-sm-9 col-9 contenu">
                <h1>Inscription</h1>
                {{ form_start(userForm) }}

                    {{ form_row(userForm.first_name, {'attr': {class : "form-control"}}) }} 
                    {{ form_row(userForm.last_name, {'attr': {class : "form-control"}}) }}
                    {{ form_row(userForm.pseudo, {'attr': {class : "form-control"}}) }}
                    {{ form_row(userForm.email, {'attr': {class : "form-control"}}) }}   
                    {{ form_row(userForm.password, {'attr' : {class : "form-control"}}) }} 
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-8">
                            {{ form_row(userForm.avatar_image) }}
                            </div>
                            <div class="col-4 mb-5">
                            {{ form_row(userForm.valider, {'attr' : {class : "btn btn-primary"}}) }}
                            </div> 
                        </div>
                    </div>

                {{ form_end(userForm) }}
                    
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/user.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% block styleFanArts %}
        <link rel="stylesheet" href="{{ asset ("styles/home.styles.css")}}">
    {% endblock %}

    <div class="container-fluid">
        <div>
            <div class="col-12">
                    
                <p>{{ user.pseudo }}</p>

            </div>
        </div>
    </div>

    

    {% for fanart in fanarts  %}

        <p>{{ fanart.fanArtTitle }}</p>
        <img src="/uploads/images/{{ fanart.fanArtSketch }}" alt="">

    {% endfor %}

{% endblock %}