src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar_image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAvatarImage(): ?string
    {
        return $this->avatar_image;
    }

    public function setAvatarImage(?string $avatar_image): self
    {
        $this->avatar_image = $avatar_image;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lilita+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset("styles/dashboard.styles.css")}}">
    <link rel="stylesheet" href="{{asset("styles/home.styles.css")}}">
    <title>{% block title %}Comics{% endblock %}</title>
    {% block styleSide %}{% endblock %}
    {% block styleFanArts %}{% endblock %}
    {% block styleCreateFanArt %}{% endblock %}
    {% block styleSignUp %}{% endblock %}
    {% block styleLog %}{% endblock %}

</head>
<body>

    {% include "header.html.twig" %} {# Header + bouton #}

    {% block body %}{% endblock %} {# Présentation home #}

    {% include "footer.html.twig" %} {# Footer #}

    {% block javascripts %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html.twig
<div class="footer">
    <div class="logo-left"></div>
    <div class="element-text">
        <p>Certaines images et photos sont les <span>propriétés exclusives</span> de</p>
        <a href="https://www.marvel.com" target="_blank"> MARVEL COMICS™</a>, 
        <a href="https://www.dccomics.com" target="_blank"> DC COMICS™</a>, 
        <a href="https://www.dccomics.com" target="_blank">DARK HORSE COMICS™</a>, 
        <a href="https://imagecomics.com" target="_blank">IMAGE COMICS™</a>
    </div>
    <div class="logo-right"></div>
</div>

templates/header.html.twig
{# Header + bouton #}
{% block body %}

    <header>
        <div class="block-middle">
            <div class="element-middle-top">
                <div class="background-middle-top"></div>
            </div>
            <div class="container">
                    <div class="row">
                    <button class="btn btn-sm col"><a href="/">Accueil</a></button>
                    <button class="btn btn-sm col"><a href="{{ path ("articles", { from : 1 }) }}">Artistes</a></button>
                    <button class="btn btn-sm col"><a href="{{ path ("fanArts", { from : 1 }) }}">Fan Arts</a></button>
                    {% if not app.user %}
                    <button class="btn btn-sm col"><a href="{{ path('create_users') }}">S'inscrire</a></button>
                    {% else %}
                    <button class="btn btn-sm col"><a href="{{ path('dashboard_user_update', { pseudo: app.user.pseudo}) }}">Compte</a></button>
                    {% endif %}
                    {% if app.user %}
                    <button class="btn btn-sm col"><a href="{{ path('logout') }}">Se déconnecter</a></button>
                    {% else %}
                        <button class="btn btn-sm col"><a href="{{ path('login') }}">Se connecter</a> </button>
                    {% endif %}
                </div>
            </div>
    </header>

{% endblock %}

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% block style %}
        <link rel="stylesheet" href="{{ asset("styles/home.styles.css") }}">
    {% endblock %}

    {% if app.user %}
        <div class="profil">
            <h4 class="centrer">{{ app.user.pseudo }}</h4>
            <div class="container">
                <div class="row">
                    <div class="col-3">
                        <img src="/uploads/images/{{ app.user.avatarImage }}" alt="" height="350px">
                    </div>
                    <div class="col-6">
                        <ul>
                            <li>Nom: {{ app.user.lastName }}</li>
                            <li>Prénom: {{ app.user.firstName }}</li>
                            <li><a href="{{ path('home', {id: app.user.id}) }}">Voir mes fanArts</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}



    {% if not app.user %}
        <div class="contenuPresentation">
            <p>Présentation</p>
            <p>Bonjour à tous et bienvenue sur ma page. Comme vous l'avez vu, c'est un site qui va parler de Comics. Pas
                de tous les comics non, je n'ai ni la prétention de tous les connaître ni de tous les lire, juste les
                comics que j'aime ou que j'ai aimé. Les Comics mais aussi les dessinateurs. Alors je sais qu'on va me
                dire qu'il en manque des tonnes mais je n'ai pas dit que je serais exhaustif, non plus. D'ailleurs mon
                but est plus que nous partagions nos connaissances et nos dessins pour ceux qui aiment "gribouiller" à
                l'occasion. Nous pourrons échanger nos avis et même nos dessins oldies ou récents, mais toujours dans le
                respect des goûts de chacun. Je serais intransigeant là-dessus! Ne soyez pas étonné non plus de voir
                beaucoup de "vieux" comics. J'avoue ne plus être autant accroc que j'ai pu l'être, pour x ou y raisons,
                je suis toujours l'actualité autant que possible car ça reste une passion pour moi mais dans la vie on
                doit faire des choix et économiquement je ne pouvais plus m'éparpiller de partout. Autre chose, si vous
                trouvez des news et actus sympas partagez les moi dans la rubrique Articles et si le site rencontre un
                peu de succès il n'est pas exclu que j'y intègre un forum, à voir. si vous poubliez des articles essayez
                d'y mettre des sources si possible ou de préciser si ce sont des rumeurs. Allez sur ce, enjoy et
                partagez vos avis!!</p>
        </div>
    {% endif %}

{% endblock %}